version: "3.9"

services:
  queue:
    image: rabbitmq:3.9.7-alpine
    volumes:
      - "./rabbitmq.d/rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./rabbitmq.d/definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"

  database:
    image: postgres:12-alpine3.14
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"